
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 07 20:04:10 CST 2014
//----------------------------------------------------

package tiger.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int FUNCTION = 31;
  public static final int GE = 8;
  public static final int STR = 48;
  public static final int UMINUS = 39;
  public static final int LPAREN = 42;
  public static final int INT = 33;
  public static final int ARRAY = 27;
  public static final int FOR = 23;
  public static final int MINUS = 3;
  public static final int RPAREN = 43;
  public static final int SEMICOLON = 17;
  public static final int AND = 13;
  public static final int LT = 10;
  public static final int NIL = 37;
  public static final int TYPE = 36;
  public static final int IN = 32;
  public static final int OR = 14;
  public static final int COMMA = 15;
  public static final int NUM = 46;
  public static final int PLUS = 2;
  public static final int ASSIGN = 29;
  public static final int IF = 19;
  public static final int ID = 47;
  public static final int DOT = 16;
  public static final int LE = 9;
  public static final int OF = 38;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOD = 6;
  public static final int NEQ = 12;
  public static final int BREAK = 30;
  public static final int EQ = 11;
  public static final int LBRACK = 40;
  public static final int TIMES = 4;
  public static final int COLON = 18;
  public static final int LBRACE = 44;
  public static final int ELSE = 21;
  public static final int RBRACK = 41;
  public static final int TO = 26;
  public static final int WHILE = 22;
  public static final int LET = 28;
  public static final int RBRACE = 45;
  public static final int THEN = 20;
  public static final int END = 24;
  public static final int STRING = 34;
  public static final int GT = 7;
  public static final int VAR = 35;
  public static final int DO = 25;
}

